[[battery]]
level = 20
urgency = "critical"
appname = "Low battery level"
summary = "Battery level at {left_percent}%!"
body = ""
icon = "battery-caution"
hints = ["transient", "category:battery", "string:x-dunst-stack-tag:battery.low"]

[[battery]]
level = 5
urgency = "critical"
appname = "Critical battery level"
summary = "Battery level at {left_percent}%!"
body = ""
icon = "battery-empty"
timeout = 0
hints = ["transient", "category:battery", "string:x-dunst-stack-tag:battery.low"]

[[memory]]
level = 90.0
urgency = "normal"
appname = "High RAM consumption"
summary = "RAM usage at {used_percent}%!"
body = "Total: {total}, left: {left}"
icon = "dialog-warning"
hints = ["transient", "category:memory", "string:x-dunst-stack-tag:memory.high"]

[[storage]]
level = 95.0
urgency = "normal"
appname = "Low disk space"
summary = "{left_percent}% of disk is available"
body = "Device {name} has {total} in total, {left} left"
icon = "drive-harddisk"
hints = ["category:storage", "string:x-dunst-stack-tag:storage.low"]

[[device]]
action = "bind"
subsystem = "usb"
urgency = "low"
appname = "USB"
summary = "Device connected"
body = "New USB device connected: {devpath}"
icon = "media-flash"
hints = ["transient", "category:usb", "string:x-dunst-stack-tag:usb.connect"]

[[device]]
action = "unbind"
subsystem = "usb"
urgency = "low"
appname = "USB"
summary = "Device disconnected"
body = "USB device disconnected: {devpath}"
icon = "media-flash"
hints = ["transient", "category:usb", "string:x-dunst-stack-tag:usb.disconnect"]

[[device]]
action = "add"
subsystem = "drm"
urgency = "low"
appname = "HDMI"
summary = "Connected"
body = "HDMI device connected"
icon = "video-display"
hints = ["transient", "category:hdmi", "string:x-dunst-stack-tag:hdmi.connect"]

[[device]]
action = "remove"
subsystem = "drm"
urgency = "low"
appname = "HDMI"
summary = "Disconnected"
body = "HDMI device disconnected"
icon = "video-display"
hints = ["transient", "category:hdmi", "string:x-dunst-stack-tag:hdmi.disconnect"]

[[device]]
action = "add"
subsystem = "sound"
urgency = "low"
appname = "Jack 3.5"
summary = "Audio device connected"
body = "Audio device connected"
icon = "audio-headphones"
hints = ["transient", "category:audio", "string:x-dunst-stack-tag:audio.connect"]

[[device]]
action = "remove"
subsystem = "sound"
urgency = "low"
appname = "Jack 3.5"
summary = "Audio device disconnected"
body = "Audio device disconnected"
icon = "audio-headphones"
hints = ["transient", "category:audio", "string:x-dunst-stack-tag:audio.disconnect"]

[[power_supply]]
name = "AC"
online = "1"
urgency = "low"
appname = "Power supply"
summary = "AC cable disconnected"
body = ""
icon = "ac-adapter"
hints = ["transient", "category:power-supply", "string:x-dunst-stack-tag:power-supply"]

[[power_supply]]
name = "AC"
online = "0"
urgency = "low"
appname = "Power supply"
summary = "AC cable connected"
body = ""
icon = "ac-adapter"
hints = ["transient", "category:power-supply", "string:x-dunst-stack-tag:power-supply"]

[network.disconnect]
urgency = "critical"
appname = "Network"
summary = "Disconnect"
body = "Network connection lost"
icon = "network-offline"
hints = ["transient", "category:network", "string:x-dunst-stack-tag:network.disconnect"]

[network.reconnect]
urgency = "normal"
appname = "Network"
summary = "Back online"
body = "Network connection restored"
icon = "network-transmit-receive"
hints = ["transient", "category:network", "string:x-dunst-stack-tag:network.reconnect"]

[bluetooth.disconnect]
urgency = "low"
appname = "Bluetooth"
summary = "Disconnection"
body = "Bluetooth device disconnected"
icon = "bluetooth-disabled"
hints = ["transient", "category:bluetooth", "string:x-dunst-stack-tag:bluetooth.disconnect"]

[bluetooth.reconnect]
urgency = "low"
appname = "Bluetooth"
summary = "Connection"
body = "Bluetooth device connected"
icon = "bluetooth-active"
hints = ["transient", "category:bluetooth", "string:x-dunst-stack-tag:bluetooth.reconnect"]
