[[battery]]
level = 20
urgency = "critical"
appname = ""
summary = "Низкий заряд батареи"
body = "Уровень заряда упал до {left_percent}%!"
icon = "battery-caution-symbolic"
hints = ["transient", "category:battery", "string:x-dunst-stack-tag:battery.low"]

[[battery]]
level = 5
urgency = "critical"
appname = ""
summary = "Критический уровень заряда батареи"
body = "Уровень заряда батареи упал до {left_percent}%!"
icon = "battery-empty-symbolic"
timeout = 0
hints = ["transient", "category:battery", "string:x-dunst-stack-tag:battery.low"]

[[cpu]]
level = 90.0
urgency = "normal"
appname = ""
summary = "ЦПУ используется на {used_percent}%!"
body = "Максимальная тактовая частота ядра: {max_freq} КГц, в среднем: {avg_freq} КГц."
icon = "dialog-warning-symbolic"
hints = ["transient", "category:cpu", "string:x-dunst-stack-tag:cpu.high"]

[[memory]]
level = 90.0
urgency = "normal"
appname = ""
summary = "ОЗУ используется на {used_percent}%!"
body = "Всего доступно {total}, осталось {left}."
icon = "dialog-warning-symbolic"
hints = ["transient", "category:memory", "string:x-dunst-stack-tag:memory.high"]

[[storage]]
level = 95.0
urgency = "normal"
appname = ""
summary = "Доступно менее {left_percent}% дискового пространства!"
body = "На устройстве {name} всего доступно {total}, осталось {left}."
icon = "drive-harddisk-symbolic"
hints = ["category:storage", "string:x-dunst-stack-tag:storage.high"]

[[device]]
action = "add"
subsystem = "block"
devtype = "disk"
urgency = "low"
appname = ""
summary = "Устройство подключено"
body = "Подключено новое USB устройство: {devnode}"
icon = "media-flash-symbolic"
hints = ["transient", "category:usb", "string:x-dunst-stack-tag:block.{devnum}"]

[[device]]
action = "remove"
subsystem = "block"
devtype = "disk"
urgency = "low"
appname = ""
summary = "Устройство отключено"
body = "USB устройство было отключено: {devnode}"
icon = "media-flash-symbolic"
hints = ["transient", "category:usb", "string:x-dunst-stack-tag:block.{devnum}"]

[[power_supply]]
type = "Mains"
online = "1"
urgency = "low"
appname = ""
summary = "Кабель питания подключён"
body = ""
icon = "ac-adapter-symbolic"
hints = ["transient", "category:power-supply", "string:x-dunst-stack-tag:power-supply"]

[[power_supply]]
type = "Mains"
online = "0"
urgency = "low"
appname = ""
summary = "Кабель питания отключён"
body = ""
icon = "ac-adapter-symbolic"
hints = ["transient", "category:power-supply", "string:x-dunst-stack-tag:power-supply"]
